import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MarkHead from "../components/markHead";
import About from "../components/about";
import Skills from "../components/skills";
import Work from "../components/work";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MarkHead />
      <About />
      <Skills />
      <Work />
    </div>
  );
};

export default Home;
